name: Deploy to Azure SWA
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: 15016022e7af0f0c5cbadc917802e841dc2f25474179e09d233c651bd264dc1007-af3d2786-b922-47cb-ab9f-1047ce588bd6000030005e673800
          repo_token: ${{ github.token }}
          action: upload
          app_location: /
          skip_app_build: true
